# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - MONGO_HOST=db
      - MONGO_DB_NAME=slackbot
      - PORT=3000
    env_file:
      - .env

  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - db:/data/db

volumes:
  db:
